title: Money ศาสตร์
suffix: Money ศาสตร์
description: website ช่วยวางแผนทางการเงิน การลงทุน การเกษียณ ด้วยเครื่องมือคำนวณ และสรุปข้อมูลข่าวสารการลงทุนรายสัปดาห์

name: Money ศาสตร์
url: "https://www.moneysart.com"
baseurl: ""
base_canonical: "https://www.moneysart.com"
permalink: 

social:
   facebook: https://www.facebook.com/moneysart
   line:
   github: https://github.com/moneysart/moneysart.github.io
   email: chatdanai.l@gmail.com

google_analytics: "G-47WXWD20WW"