title: เรื่องเงิน สำคัญ (Money Matters)
description: website ช่วยวางแผนทางการเงิน การลงทุน การเกษียณ ด้วยเครื่องมือคำนวณ และสรุปข้อมูลข่าวสารการลงทุนรายสัปดาห์

name: moneymattersthailand
url: "https://www.moneymattersthailand.com"
baseurl: ""
base_canonical: "https://www.moneymattersthailand.com"
permalink: 

social:
   facebook: https://www.facebook.com/moneymattersthailand
   line:
   github: https://github.com/moneymattersthailand/moneymattersthailand.github.io
   email: chatdanai.l@gmail.com

google_analytics: "G-47WXWD20WW"